### ISSUE TITLE
Take a picture

### ISSUE THREAD

**Issue by AndreFelippeVidal** [darkerego/androrat-stealth#1]
Hi, 

I decided to try this version of androrat for androi studio..

Everything is running ok, except taking pictures, streaming videos and location.

Do you know what can be wrong?

**Comment by darkerego** [comment]
Hello, sorry it took me a while to get back to you. As far as i know, the camera functionality is broken, and only works when the app is not running in the background. Location, however, should work fine, I have had no issues with that. What device and version of Android are you testing on?
